// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

import { SerializationStyle } from '../../http/serialization/base-serializer.js';
import { RequestBuilder } from '../../http/transport/request-builder.js';
import { ContentType, HttpResponse, RequestConfig } from '../../http/types.js';
import { BaseService } from '../base-service.js';
import { ArrayOfEvents, arrayOfEventsResponse } from './models/array-of-events.js';
import { Event, eventResponse } from './models/event.js';
import { ListEventsParams } from './request-params.js';

export class EventsService extends BaseService {
  /**
   * Retrieves a paginated list of events for the project.
   * @param {number} [limit] -
   * @param {string} [startingAfter] -
   * @param {string} [endingBefore] -
   * @returns {Promise<HttpResponse<ArrayOfEvents>>} OK
   */
  async listEvents(params?: ListEventsParams, requestConfig?: RequestConfig): Promise<HttpResponse<ArrayOfEvents>> {
    const request = new RequestBuilder()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('GET')
      .setPath('/events')
      .setRequestSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .addResponse({
        schema: arrayOfEventsResponse,
        contentType: ContentType.Json,
        status: 200,
      })
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'limit',
        value: params?.limit,
      })
      .addQueryParam({
        key: 'starting_after',
        value: params?.startingAfter,
      })
      .addQueryParam({
        key: 'ending_before',
        value: params?.endingBefore,
      })
      .build();
    return this.client.call<ArrayOfEvents>(request);
  }

  /**
   * Retrieves a paginated list of events for the project.
   * @param {string} id -
   * @returns {Promise<HttpResponse<Event>>} OK
   */
  async getEvent(id: string, requestConfig?: RequestConfig): Promise<HttpResponse<Event>> {
    const request = new RequestBuilder()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('GET')
      .setPath('/events/{id}')
      .setRequestSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .addResponse({
        schema: eventResponse,
        contentType: ContentType.Json,
        status: 200,
      })
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'id',
        value: id,
      })
      .build();
    return this.client.call<Event>(request);
  }
}
