// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

import { SerializationStyle } from '../../http/serialization/base-serializer.js';
import { RequestBuilder } from '../../http/transport/request-builder.js';
import { ContentType, HttpResponse, RequestConfig } from '../../http/types.js';
import { BaseService } from '../base-service.js';
import { ArrayOfUsers, arrayOfUsersResponse } from './models/array-of-users.js';
import { ListUsersParams } from './request-params.js';

export class UsersService extends BaseService {
  /**
   *
   * @param {number} [limit] -
   * @param {string} [startingAfter] -
   * @param {string} [endingBefore] -
   * @returns {Promise<HttpResponse<ArrayOfUsers>>} OK
   */
  async listUsers(params?: ListUsersParams, requestConfig?: RequestConfig): Promise<HttpResponse<ArrayOfUsers>> {
    const request = new RequestBuilder()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('GET')
      .setPath('/users')
      .setRequestSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .addResponse({
        schema: arrayOfUsersResponse,
        contentType: ContentType.Json,
        status: 200,
      })
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'limit',
        value: params?.limit,
      })
      .addQueryParam({
        key: 'starting_after',
        value: params?.startingAfter,
      })
      .addQueryParam({
        key: 'ending_before',
        value: params?.endingBefore,
      })
      .build();
    return this.client.call<ArrayOfUsers>(request);
  }
}
