// This file was generated by liblab | https://liblab.com/

export interface GetDeliveryconfigParams {
  key?: string;
}

export interface GetMobilePushApnsUserTokensParams {
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
}

export interface GetMobilePushExpoUserTokensParams {
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
}

export interface GetMobilePushFcmUserTokensParams {
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
}

export interface GetSlackUserTokensParams {
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
}

export interface GetTeamsUserTokensParams {
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
}

export interface GetWebPushUserTokensParams {
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
}
