// This file was generated by liblab | https://liblab.com/

export interface FetchProjectTokensParams {
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
}

export interface FetchUserTokensParams {
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
}
